adding mobile menu to Portfolio page.
jossi30/My-Portfolio pull request #15
Opened 2022-10-11 05:31 UTC by jossi30

adding a mobile menu that opens and closes by clicking the nav bar and nav links.

2022-10-11 05:50 UTC, tufoinnkuo10 requested changes
Hi @jossi30 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ Mobile menu hamburger works as expected
✅ Menu close icon works perfectly well

Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-10-11 05:50 UTC, tufoinnkuo10 commented on index.html
> +        <a href="#" class="logo">jossi30</a>
- [ ] great job so far, everything works fine. please ensure that the social icons are not showing on the menu popup so as to follow the figma design. great job.
![Screenshot (507)_LI](https://user-images.githubusercontent.com/65298048/195006648-404b1939-f405-4dda-896a-a91a78c62834.jpg)

2022-10-11 05:50 UTC, tufoinnkuo10 commented on index.html
> +        <ul class="nav-menu">
- [ ] kindly ensure that when the menu comes up, it should not be posible to scroll through your portfolio unless using the menu links or when the menu is closed.
![Screenshot (508)_LI](https://user-images.githubusercontent.com/65298048/195006933-86ca58ea-cce0-4ffb-a76b-a15756588338.jpg)

2022-10-11 20:52 UTC, ShahierNashaat requested changes
Hi @jossi30, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯 

- Correct use of GitFlow ✔️
- Descriptive commit messages ✔️
- Professional looking pull request ✔️
- Your readme looks professional ✔️
- Good overall design ✔️
- Your code is clean and well documented ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-11 20:52 UTC, ShahierNashaat commented on index.html
> +      <li><a onclick="myFunction()" href="#contact-me-id">Contact</a></li>
- [ ] Kindly write `href` values correct so the links work properly.

```html
<li><a onclick="myFunction()" href="#works">Portoflio</a></li>
<li><a onclick="myFunction()" href="#about-myself">About</a></li>
<li><a onclick="myFunction()" href="#contact-me">Contact</a></li>
```

2022-10-12 05:48 UTC, CollinsTatang approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-12 05:51 UTC, merged