made changes that makes the page fit desktop screens using RWD
jossi30/My-Portfolio pull request #8
Opened 2022-09-29 12:35 UTC by jossi30

added some feature to make the mobile version fit to larger screens using responsive web design

2022-09-29 13:23 UTC, mckent05 requested changes
Hi @jossi30 , 

# STATUS : CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/193042055-7306c6a5-4a4a-4bca-a57c-2932dc448f94.gif)

## Highlights
- Your portfolio is looking really great 👍 👍 
- Descriptive PR title and summary 💯 💯 
- All linter checks are passing ✔️ ✔️ 


## Required Changes ♻️
- Please check the mobile version of your portfolio, you have a bug in the about myself section.  Please try to fix this 🙏 🙏 

Your design:
![youisef mobile](https://user-images.githubusercontent.com/73607512/193042889-b91d7a43-941e-4c21-a12a-f7a0036e35dc.PNG)

_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 13:23 UTC, mckent05 commented on style.css
> +  }
- There are some little differences between the project card in your desktop design and the one in the Figma template. Please fix this for all your project cards as they may apply. Remember it is important that you try to replicate the Figma design as closely as possible to give confidence to recruiters in your ability to produce exact business requirements 🙏

Your design -
- Please pay attention to the following
-- The tech stack design (HTML, CSS, Javascript) is not the same as it is in the design
-- The `See project` button is not the same as it is in the design
-- The project cards have a border around them.
![roject card youisef](https://user-images.githubusercontent.com/73607512/193037327-f1cba7c6-26eb-450c-b15a-79cb7ae27cb7.PNG)

Figma design -
![project card project](https://user-images.githubusercontent.com/73607512/193038307-1d073704-3762-465c-8b69-983b84f65976.PNG)

2022-09-29 13:23 UTC, mckent05 commented on style.css
> +  }
- Good job on the work done but your nav doesn't exactly match the Figma design. Remember it is important that you try to replicate the Figma design as closely as possible to give confidence to recruiters in your ability to produce exact business requirements 🙏

Your design (please pay attention to the margins I have alighted. The margins aren't equal. Please try to fix this)-
![nav youisef](https://user-images.githubusercontent.com/73607512/193038886-e48e1e2e-76fa-49fa-ba50-97a03345d27b.PNG)

Figma template -
![nav figma1](https://user-images.githubusercontent.com/73607512/193039034-55e38d64-3fb9-4b6a-9463-4e936df48026.PNG)

2022-09-29 13:23 UTC, mckent05 commented on style.css
> +  }
- There are slight differences between your design for the `about myself` section and the given Figma template. Please ty to fix this.

Your design(Pay attention to the alignment of the arrows) -
![tech stack youisef](https://user-images.githubusercontent.com/73607512/193040859-2801e031-0c12-410c-a3fc-8c4e6a619fd8.PNG)

Figma template-
![tech stack desktop](https://user-images.githubusercontent.com/73607512/193040938-edcc11f3-f3a5-4c30-955a-126aa7d64b7c.PNG)

2022-09-30 02:16 UTC, roshan-bajgain requested changes
Hi @jossi30, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 02:16 UTC, roshan-bajgain commented on index.html
> +                    <li class="lang name">javascript</li>
- [ ] I would suggest you please, fix that the page is divided half of it contains the project's picture and the other half contains the project's description. As requested by the previous reviewer please fix the spacing by seeing the design
- [ ] please fix the buttons as well
### Figma design
![figma](https://user-images.githubusercontent.com/81727988/193173906-135a19a5-3229-4875-affb-3897128a3dc3.png)
### Your design
![your](https://user-images.githubusercontent.com/81727988/193173934-2a40585f-69e8-454c-84cf-1544698c7c61.png)

2022-09-30 02:16 UTC, roshan-bajgain commented on index.html
> +                          </div>
- [ ] If you see the nav links then It is aligned at right so please fix it. See the design for reference
### Figma design
![figma](https://user-images.githubusercontent.com/81727988/193174543-defd1ed2-a6f9-462f-890f-d2344f5661dd.png)
### Your design
![your](https://user-images.githubusercontent.com/81727988/193174567-ad11a5f4-e2d4-433c-b295-1165eee24aef.png)

2022-09-30 02:16 UTC, roshan-bajgain commented on index.html
> +        </div>
- [ ] There are 2 blocks The left one takes 40% and the right one the remaining 60% of the page's width, and the contents of each of them are aligned to the right. please see the design below and make changes
### Figma design
![figma](https://user-images.githubusercontent.com/81727988/193175033-5fd9671c-13d6-45c7-bd2a-ebeecac0742e.png)
### Your design
![your](https://user-images.githubusercontent.com/81727988/193175069-7169fe78-2e5d-495c-ac86-7362855eeeaa.png)

2022-09-30 02:16 UTC, roshan-bajgain commented on index.html
> +        </div>
- [ ] As requested by the previous reviewer, please make your about section match the design. As both, the content is aligned at the same line and there is more spacing on the right side
### your mobile design
![yourmbl](https://user-images.githubusercontent.com/81727988/193175462-98ffec07-a8d0-4a3e-afeb-7207d80aab30.png)
### Fimga of the mobile version
![figma](https://user-images.githubusercontent.com/81727988/193175690-f54ceb46-a51f-4ac5-bda0-a3dd1e4a1a48.png)

2022-09-30 10:19 UTC, Qoosim approved these changes
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @jossi30, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

-   No linter errors. :heavy_check_mark: 
-   Good README. :heavy_check_mark: 
-   Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/f4e04d5e9518e3cbf972fb0f7611848a87ed4e1aa7770811bc22c5b957824887/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6c3253716972355a78666f5332374576532f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 10:25 UTC, merged